/* solos_ish.c — the iSH kernel, embedded. See solos_ish.h.
 *
 * Boots the kernel on an unpacked fakefs rootfs, starts guest processes with
 * host pipes or a pseudo-terminal for their stdio, reports their exits, and
 * keeps the guest's resolver configuration in step with the host's network.
 */

#include "solos_ish.h"

#include <errno.h>
#include <fcntl.h>
#include <limits.h>
#include <netdb.h>
#include <pthread.h>
#include <resolv.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <ucontext.h>
#include <unistd.h>

#include <Network/Network.h>
#include <dispatch/dispatch.h>
#include <mach/mach.h>
#include <os/proc.h>
#include <sys/sysctl.h>
#include <TargetConditionals.h>

/* Kernel headers, from the iSH source tree (see build.rs for the paths). */
#include "misc.h"
#include "debug.h"
#include "kernel/init.h"
#include "kernel/task.h"
#include "kernel/calls.h"
#include "kernel/fs.h"
#include "kernel/signal.h"
#include "kernel/errno.h"
#include "kernel/mm.h"
#include "fs/fd.h"
#include "fs/devices.h"
#include "fs/fake.h"
#include "fs/fake-db.h"
#include "fs/path.h"
#include "fs/real.h"
#include "fs/tty.h"
#include "cpu-offsets.h"

/* ------------------------------------------------------------------ */
/* JIT crash recovery                                                  */
/* ------------------------------------------------------------------ */

/* Thread-locals the emulator maintains; see asbestos.c in the kernel fork. */
extern __thread volatile sig_atomic_t in_jit;
extern __thread volatile uint64_t jit_saved_pc;
extern __thread int ish_thread_marker;
extern void jit_crash_trampoline(void);
extern void (*die_handler)(const char *msg);

static void park_thread_forever(void) {
    /* pthread_exit trips SIGTRAP on iOS in some thread states, which would
     * take the whole app down. A guest thread is expendable; parking it is
     * not. */
    sigset_t all;
    sigfillset(&all);
    pthread_sigmask(SIG_BLOCK, &all, NULL);
    select(0, NULL, NULL, NULL, NULL);
    __builtin_unreachable();
}

static void jit_crash_handler(int sig, siginfo_t *info, void *ctx) {
#ifdef __aarch64__
    if ((sig == SIGSEGV || sig == SIGBUS) && in_jit) {
        /* A stale TLB pointer from a concurrent copy-on-write. Rewrite the
         * guest's saved state and resume in the trampoline, which returns
         * control to the kernel as a guest fault rather than a host crash.
         * Offsets come from the cpu-offsets.h generated by this very build,
         * never hardcoded. */
        ucontext_t *uc = (ucontext_t *)ctx;
        uint64_t cpu_ptr = uc->uc_mcontext->__ss.__x[1];
        uint64_t x7 = uc->uc_mcontext->__ss.__x[7];
        uint64_t x10 = uc->uc_mcontext->__ss.__x[10];
        uint64_t guest_addr = (x7 - x10) & 0xffffffffffffULL;
        uint64_t esr = uc->uc_mcontext->__es.__esr;
        int was_write = (esr & 0x40) != 0;

        *(uint64_t *)(cpu_ptr + CPU_segfault_addr) = guest_addr;
        *(int *)(cpu_ptr + CPU_segfault_was_write) = was_write;
        *(uint64_t *)(cpu_ptr + CPU_pc) = (uint64_t)jit_saved_pc;
        uc->uc_mcontext->__ss.__sp = *(uint64_t *)(cpu_ptr + LOCAL_jit_exit_sp);
        uc->uc_mcontext->__ss.__pc = (uint64_t)jit_crash_trampoline;

        sigset_t unblock;
        sigemptyset(&unblock);
        sigaddset(&unblock, sig);
        sigprocmask(SIG_UNBLOCK, &unblock, NULL);
        return;
    }
#endif
    if (!ish_thread_marker) {
        /* Not a guest thread: this is a genuine crash in the host app, and
         * intercepting it would hide the report. Restore and re-raise. */
        struct sigaction dfl;
        memset(&dfl, 0, sizeof dfl);
        dfl.sa_handler = SIG_DFL;
        sigaction(sig, &dfl, NULL);
        raise(sig);
        return;
    }
    char buf[192];
    int n = snprintf(buf, sizeof buf, "\n[solos-ish] guest crash: signal %d at %p\n", sig, info->si_addr);
    write(STDERR_FILENO, buf, (size_t)n);
    park_thread_forever();
}

static void solos_die_handler(const char *msg) {
    char buf[512];
    int n = snprintf(buf, sizeof buf, "\n[solos-ish] kernel die(): %s\n", msg ? msg : "(null)");
    write(STDERR_FILENO, buf, (size_t)n);
    park_thread_forever();
}

static void install_crash_handler(void) {
    static char altstack[SIGSTKSZ];
    stack_t ss;
    ss.ss_sp = altstack;
    ss.ss_size = SIGSTKSZ;
    ss.ss_flags = 0;
    sigaltstack(&ss, NULL);

    struct sigaction sa;
    memset(&sa, 0, sizeof sa);
    sa.sa_sigaction = jit_crash_handler;
    sa.sa_flags = SA_SIGINFO | SA_ONSTACK;
    sigaction(SIGSEGV, &sa, NULL);
    sigaction(SIGBUS, &sa, NULL);
    sigaction(SIGILL, &sa, NULL);
    sigaction(SIGTRAP, &sa, NULL);
    /* SIGABRT is deliberately left alone: it belongs to assert(), malloc and
     * the host runtime, and swallowing it would mask real failures. */
}

/* ------------------------------------------------------------------ */
/* Console TTY — only ever used for init's own stdio                   */
/* ------------------------------------------------------------------ */

static int solos_tty_write(struct tty *tty, const void *buf, size_t len, bool blocking) {
    (void)tty; (void)blocking;
    if (len) write(STDERR_FILENO, buf, len);
    return (int)len;
}
static int solos_tty_init(struct tty *tty) { (void)tty; return 0; }
static void solos_tty_cleanup(struct tty *tty) { (void)tty; }
static struct tty_driver_ops solos_console_ops = {
    .init = solos_tty_init,
    .write = solos_tty_write,
    .cleanup = solos_tty_cleanup,
};
DEFINE_TTY_DRIVER(solos_console_driver, &solos_console_ops, TTY_CONSOLE_MAJOR, 8);

/* ------------------------------------------------------------------ */
/* Exit notification                                                    */
/* ------------------------------------------------------------------ */

static solos_ish_exit_cb g_exit_cb = NULL;
static void *g_exit_ctx = NULL;

static void on_task_exit(struct task *task, int code) {
    /* Only init's direct children matter to us: deeper descendants are the
     * guest's own business, and walking them here contends with the kernel's
     * wait path for pids_lock. */
    if (task->parent != NULL && task->parent->parent != NULL) return;
    solos_ish_exit_cb cb = g_exit_cb;
    void *ctx = g_exit_ctx;
    if (cb) cb((int)task->pid, code, ctx);
}

void solos_ish_set_exit_handler(solos_ish_exit_cb cb, void *ctx) {
    g_exit_ctx = ctx;
    g_exit_cb = cb;
}

/* ------------------------------------------------------------------ */
/* Boot                                                                 */
/* ------------------------------------------------------------------ */

static pthread_mutex_t g_lock = PTHREAD_MUTEX_INITIALIZER;
static int g_booted = 0;

int solos_ish_is_booted(void) { return g_booted; }

static void create_device_nodes(void) {
    generic_mkdirat(AT_PWD, "/dev", 0755);
    generic_mkdirat(AT_PWD, "/dev/pts", 0755);
    for (int i = 1; i <= 7; i++) {
        char name[16];
        snprintf(name, sizeof name, "/dev/tty%d", i);
        generic_mknodat(AT_PWD, name, S_IFCHR | 0666, dev_make(TTY_CONSOLE_MAJOR, i));
    }
    generic_mknodat(AT_PWD, "/dev/tty", S_IFCHR | 0666, dev_make(TTY_ALTERNATE_MAJOR, DEV_TTY_MINOR));
    generic_mknodat(AT_PWD, "/dev/console", S_IFCHR | 0666, dev_make(TTY_ALTERNATE_MAJOR, DEV_CONSOLE_MINOR));
    generic_mknodat(AT_PWD, "/dev/ptmx", S_IFCHR | 0666, dev_make(TTY_ALTERNATE_MAJOR, DEV_PTMX_MINOR));
    generic_mknodat(AT_PWD, "/dev/null", S_IFCHR | 0666, dev_make(MEM_MAJOR, DEV_NULL_MINOR));
    generic_mknodat(AT_PWD, "/dev/zero", S_IFCHR | 0666, dev_make(MEM_MAJOR, DEV_ZERO_MINOR));
    generic_mknodat(AT_PWD, "/dev/full", S_IFCHR | 0666, dev_make(MEM_MAJOR, DEV_FULL_MINOR));
    generic_mknodat(AT_PWD, "/dev/random", S_IFCHR | 0666, dev_make(MEM_MAJOR, DEV_RANDOM_MINOR));
    generic_mknodat(AT_PWD, "/dev/urandom", S_IFCHR | 0666, dev_make(MEM_MAJOR, DEV_URANDOM_MINOR));
}

/* Defined with the rest of the DNS code, below. */
static void start_dns_watch(void);

/* The kernel's memory admission, fed as iSH's own app feeds it
 * (app/AppDelegate.m, upstream e4f540d2). Without a feed the kernel keeps a
 * fixed ledger cap, and V8's startup commitment (about 640 MB of cage) runs
 * into it: node aborted (upstream 2d0094ad) or, once the footprint governor
 * came in (6d1178f3), waited three minutes and did nothing (measured; the
 * same binary ran in a second under the reference app's older kernel).
 * The governor needs the two numbers jetsam acts on, the app's physical
 * footprint and its remaining allowance, every 250 ms; a feed older than 2 s
 * reads as "brake", so a dead sampler refuses memory rather than grant it. */
/* The app's remaining memory allowance. The simulator has no jetsam and
 * os_proc_available_memory() answers 0 there (measured), which would leave
 * the governor off and node failing; there, half the Mac's memory stands in.
 * Devices always use the real allowance. */
static uint64_t available_memory(void) {
    uint64_t avail = (uint64_t)os_proc_available_memory();
#if TARGET_OS_SIMULATOR
    if (avail == 0) {
        uint64_t mem = 0;
        size_t len = sizeof mem;
        if (sysctlbyname("hw.memsize", &mem, &len, NULL, 0) == 0) avail = mem / 2;
    }
#endif
    return avail;
}

static void memory_governor_tick(bool pressure_critical) {
    task_vm_info_data_t info;
    mach_msg_type_number_t count = TASK_VM_INFO_COUNT;
    uint64_t footprint = 0;
    if (task_info(mach_task_self(), TASK_VM_INFO, (task_info_t)&info, &count) == KERN_SUCCESS)
        footprint = info.phys_footprint;
    uint64_t avail = available_memory();
    if (footprint == 0 || avail == 0) return; /* the kernel's staleness rule covers it */
    ish_set_memory_status(footprint + avail, avail, pressure_critical);
}

static void start_memory_governor(void) {
    /* The ledger cap from the device's real allowance: the fallback when the
     * governor can never measure. Host pages, not guest ones: each committed
     * guest page occupies a whole host page. */
    size_t avail = (size_t)available_memory();
    size_t host_page = (size_t)sysconf(_SC_PAGESIZE);
    if (avail > 0 && host_page > 0)
        ish_set_anon_page_limit((long)((double)avail * 0.8 / (double)host_page));
    fprintf(stderr, "solos_ish: memory governor: available %zu MB, host page %zu KB\n",
            avail / (1024 * 1024), host_page / 1024);

    static dispatch_source_t timer, pressure;
    dispatch_queue_t q = dispatch_get_global_queue(QOS_CLASS_UTILITY, 0);
    timer = dispatch_source_create(DISPATCH_SOURCE_TYPE_TIMER, 0, 0, q);
    dispatch_source_set_timer(timer, DISPATCH_TIME_NOW, 250 * NSEC_PER_MSEC, 50 * NSEC_PER_MSEC);
    dispatch_source_set_event_handler(timer, ^{ memory_governor_tick(false); });
    dispatch_resume(timer);
    pressure = dispatch_source_create(DISPATCH_SOURCE_TYPE_MEMORYPRESSURE, 0,
                                      DISPATCH_MEMORYPRESSURE_WARN | DISPATCH_MEMORYPRESSURE_CRITICAL, q);
    dispatch_source_set_event_handler(pressure, ^{
        memory_governor_tick((dispatch_source_get_data(pressure) & DISPATCH_MEMORYPRESSURE_CRITICAL) != 0);
    });
    dispatch_resume(pressure);
    /* A first feed now, so the governor is on before any guest process runs. */
    memory_governor_tick(false);
}

int solos_ish_boot(const char *rootfs_dir) {
    if (rootfs_dir == NULL) return SOLOS_ISH_ERR_ARGS;
    pthread_mutex_lock(&g_lock);
    if (g_booted) {
        pthread_mutex_unlock(&g_lock);
        return SOLOS_ISH_OK;
    }

    install_crash_handler();
    die_handler = solos_die_handler;
    start_memory_governor();

    char data_path[PATH_MAX];
    snprintf(data_path, sizeof data_path, "%s/data", rootfs_dir);

    int err = mount_root(&fakefs, data_path);
    if (err < 0) {
        pthread_mutex_unlock(&g_lock);
        return SOLOS_ISH_ERR_BOOT;
    }
    /* fakefs suppresses bind mounts that would contain the rootfs itself, and
     * the check is against the canonical path. */
    char canonical[PATH_MAX];
    if (realpath(data_path, canonical) != NULL) fakefs_set_rootfs_data_path(canonical);

    err = become_first_process();
    if (err < 0) {
        pthread_mutex_unlock(&g_lock);
        return SOLOS_ISH_ERR_BOOT;
    }
    current->thread = pthread_self();

    create_device_nodes();
    do_mount(&procfs, "proc", "/proc", "", 0);
    do_mount(&devptsfs, "devpts", "/dev/pts", "", 0);

    exit_hook = on_task_exit;
    tty_drivers[TTY_CONSOLE_MAJOR] = &solos_console_driver;
    set_console_device(TTY_CONSOLE_MAJOR, 1);
    create_stdio("/dev/console", TTY_CONSOLE_MAJOR, 1); /* non-fatal if it fails */

    g_booted = 1;
    pthread_mutex_unlock(&g_lock);

    /* Outside the lock: the first update handler runs as soon as this starts,
     * and it writes resolv.conf. */
    start_dns_watch();
    return SOLOS_ISH_OK;
}

/* fakefs keeps its own inode records beside the host files; a directory
 * that exists only on the host is invisible to the guest's `stat`. A bind
 * mount records the mount point itself but not its parents, so `/solos` was
 * missing and `mkdir -p /solos/ws/x` failed at the first step. Each parent
 * of the mount point is made on the host and recorded if it is not. */
extern struct mount *g_fakefs_mount;

static void record_guest_parents(const char *guest_path) {
    if (g_fakefs_mount == NULL) return;
    struct fakefs_db *fs = &g_fakefs_mount->fakefs;
    char buf[PATH_MAX];
    size_t n = strlen(guest_path);
    if (n == 0 || n >= sizeof buf) return;
    memcpy(buf, guest_path, n + 1);
    for (size_t i = 1; i < n; i++) {
        if (buf[i] != '/') continue;
        buf[i] = '\0';
        mkdirat(g_fakefs_mount->root_fd, buf + 1, 0755); /* EEXIST is fine */
        db_begin_write(fs);
        if (path_get_inode(fs, buf) == 0) {
            struct ish_stat st = { .mode = S_IFDIR | 0755, .uid = 0, .gid = 0, .rdev = 0 };
            path_create(fs, buf, &st);
        }
        db_commit(fs);
        buf[i] = '/';
    }
}

int solos_ish_bind_mount(const char *guest_path, const char *host_path, int read_only) {
    if (!g_booted) return SOLOS_ISH_ERR_NOT_BOOTED;
    if (!guest_path || !host_path) return SOLOS_ISH_ERR_ARGS;
    record_guest_parents(guest_path);
    return fakefs_bind_mount(guest_path, host_path, read_only != 0);
}

int solos_ish_bind_unmount(const char *guest_path) {
    if (!g_booted) return SOLOS_ISH_ERR_NOT_BOOTED;
    if (!guest_path) return SOLOS_ISH_ERR_ARGS;
    return fakefs_bind_unmount(guest_path);
}

/* ------------------------------------------------------------------ */
/* Spawn                                                                */
/* ------------------------------------------------------------------ */

/* do_execve takes argv and envp as one NUL-separated, double-NUL-terminated
 * buffer each, because that is how the guest ABI lays them out. */
static int pack_strings(const char *const *items, char *buf, size_t cap, int *count_out) {
    size_t pos = 0;
    int count = 0;
    for (const char *const *p = items; p && *p; p++) {
        size_t len = strlen(*p) + 1;
        if (pos + len >= cap - 1) return -1;
        memcpy(buf + pos, *p, len);
        pos += len;
        count++;
    }
    buf[pos] = '\0';
    if (count_out) *count_out = count;
    return 0;
}

static int attach_pipe_fd(struct task *task, int slot, int host_fd) {
    struct fd *fd = adhoc_fd_create(&realfs_fdops);
    if (fd == NULL) return -1;
    int dup_fd = dup(host_fd);
    if (dup_fd < 0) return -1;
    fd->real_fd = dup_fd;
    task->files->files[slot] = fd;
    return 0;
}

int solos_ish_spawn(const char *path,
                   const char *const *argv,
                   const char *const *envp,
                   solos_ish_proc *out) {
    if (!g_booted) return SOLOS_ISH_ERR_NOT_BOOTED;
    if (!path || !argv || !out) return SOLOS_ISH_ERR_ARGS;

    static char argv_buf[16384];
    static char envp_buf[16384];
    int argc = 0;

    int in_pipe[2] = {-1, -1}, out_pipe[2] = {-1, -1}, err_pipe[2] = {-1, -1};
    if (pipe(in_pipe) < 0 || pipe(out_pipe) < 0 || pipe(err_pipe) < 0) {
        for (int i = 0; i < 2; i++) {
            if (in_pipe[i] >= 0) close(in_pipe[i]);
            if (out_pipe[i] >= 0) close(out_pipe[i]);
            if (err_pipe[i] >= 0) close(err_pipe[i]);
        }
        return SOLOS_ISH_ERR_PIPE;
    }

    /* `current` is thread-local and become_new_init_child overwrites it, so
     * the whole spawn runs under the lock and restores the caller's value. */
    pthread_mutex_lock(&g_lock);

    if (pack_strings(argv, argv_buf, sizeof argv_buf, &argc) < 0 ||
        pack_strings(envp, envp_buf, sizeof envp_buf, NULL) < 0) {
        pthread_mutex_unlock(&g_lock);
        goto fail;
    }

    struct task *saved = current;
    int err = become_new_init_child();
    if (err < 0) {
        current = saved;
        pthread_mutex_unlock(&g_lock);
        goto fail;
    }
    struct task *task = current;

    if (attach_pipe_fd(task, 0, in_pipe[0]) < 0 ||
        attach_pipe_fd(task, 1, out_pipe[1]) < 0 ||
        attach_pipe_fd(task, 2, err_pipe[1]) < 0) {
        current = saved;
        pthread_mutex_unlock(&g_lock);
        goto fail;
    }

    err = do_execve(path, (size_t)argc, argv_buf, envp_buf);
    if (err < 0) {
        current = saved;
        pthread_mutex_unlock(&g_lock);
        goto fail;
    }

    out->pid = (int)task->pid;
    task_start(task);
    current = saved;
    pthread_mutex_unlock(&g_lock);

    /* The guest holds its own dups; these ends belong to the child only. */
    close(in_pipe[0]);
    close(out_pipe[1]);
    close(err_pipe[1]);
    out->stdin_write = in_pipe[1];
    out->stdout_read = out_pipe[0];
    out->stderr_read = err_pipe[0];
    return SOLOS_ISH_OK;

fail:
    close(in_pipe[0]); close(in_pipe[1]);
    close(out_pipe[0]); close(out_pipe[1]);
    close(err_pipe[0]); close(err_pipe[1]);
    return SOLOS_ISH_ERR_SPAWN;
}

/* ------------------------------------------------------------------ */
/* Pseudo-terminal                                                      */
/* ------------------------------------------------------------------ */

/* The host is the terminal. The guest gets a real slave tty from the kernel's
 * own pty code, which is what makes job control, canonical mode and SIGWINCH
 * behave; everything the program prints comes back out through this one
 * callback (mirrors what iSH's own Terminal.m does). */
static solos_ish_pty_out_cb g_pty_cb = NULL;
static void *g_pty_cb_ctx = NULL;

/* Live terminals by the id handed to the caller, so input and resize can find
 * one again without the caller holding a kernel pointer. */
#define SOLOS_MAX_PTYS 16
static struct tty *g_ptys[SOLOS_MAX_PTYS];
static pthread_mutex_t g_pty_lock = PTHREAD_MUTEX_INITIALIZER;

void solos_ish_set_pty_handler(solos_ish_pty_out_cb cb, void *ctx) {
    pthread_mutex_lock(&g_pty_lock);
    g_pty_cb = cb;
    g_pty_cb_ctx = ctx;
    pthread_mutex_unlock(&g_pty_lock);
}

static struct tty *pty_by_id(int pty_id) {
    if (pty_id < 0 || pty_id >= SOLOS_MAX_PTYS) return NULL;
    pthread_mutex_lock(&g_pty_lock);
    struct tty *tty = g_ptys[pty_id];
    pthread_mutex_unlock(&g_pty_lock);
    return tty;
}

static int solos_pty_init(struct tty *tty) {
    tty->data = NULL;
    return 0;
}

static int solos_pty_write(struct tty *tty, const void *buf, size_t len, bool blocking) {
    (void) blocking;
    pthread_mutex_lock(&g_pty_lock);
    solos_ish_pty_out_cb cb = g_pty_cb;
    void *ctx = g_pty_cb_ctx;
    pthread_mutex_unlock(&g_pty_lock);
    if (cb) cb(tty->num, (const char *) buf, (int) len, ctx);
    return (int) len;
}

static void solos_pty_cleanup(struct tty *tty) {
    pthread_mutex_lock(&g_pty_lock);
    if (tty->num >= 0 && tty->num < SOLOS_MAX_PTYS && g_ptys[tty->num] == tty)
        g_ptys[tty->num] = NULL;
    pthread_mutex_unlock(&g_pty_lock);
}

static struct tty_driver_ops solos_pty_ops = {
    .init = solos_pty_init,
    .write = solos_pty_write,
    .cleanup = solos_pty_cleanup,
};

/* Declared without DEFINE_TTY_DRIVER on purpose: pty_open_fake overwrites the
 * ttys table with the pty slave driver's own. */
static struct tty_driver solos_pty_driver = {.ops = &solos_pty_ops};

/* One end of the terminal as a file descriptor the child can hold.
 *
 * Opened through /dev/pts/<n> rather than attached as an adhoc fd, because a
 * descriptor with no path behind it is only half a terminal: the ioctls work,
 * so isatty() is happy, but ttyname() has nothing to return and anything that
 * asks which terminal it is on — `tty`, `who`, a shell deciding whether it is
 * interactive — gets the wrong answer. */
static int attach_tty_fd(struct task *task, int slot, int pty_num) {
    char path[64];
    snprintf(path, sizeof path, "/dev/pts/%d", pty_num);
    struct fd *fd = generic_open(path, O_RDWR_, 0);
    if (IS_ERR(fd)) return -1;
    task->files->files[slot] = fd;
    return 0;
}

int solos_ish_spawn_pty(const char *path,
                       const char *const *argv,
                       const char *const *envp,
                       int rows,
                       int cols,
                       solos_ish_pty *out) {
    if (!g_booted) return SOLOS_ISH_ERR_NOT_BOOTED;
    if (!path || !argv || !out) return SOLOS_ISH_ERR_ARGS;

    static char argv_buf[16384];
    static char envp_buf[16384];
    int argc = 0;

    pthread_mutex_lock(&g_lock);

    if (pack_strings(argv, argv_buf, sizeof argv_buf, &argc) < 0 ||
        pack_strings(envp, envp_buf, sizeof envp_buf, NULL) < 0) {
        pthread_mutex_unlock(&g_lock);
        return SOLOS_ISH_ERR_ARGS;
    }

    /* The task has to exist first. Allocating the pty touches the guest
     * filesystem, and that reads `current` — which is NULL on the thread this
     * call arrives on, because it has never been a guest task. */
    struct task *saved = current;
    int err = become_new_init_child();
    if (err < 0) {
        current = saved;
        pthread_mutex_unlock(&g_lock);
        return SOLOS_ISH_ERR_SPAWN;
    }
    struct task *task = current;

    struct tty *tty = pty_open_fake(&solos_pty_driver);
    if (IS_ERR(tty) || tty->num < 0 || tty->num >= SOLOS_MAX_PTYS) {
        current = saved;
        pthread_mutex_unlock(&g_lock);
        return SOLOS_ISH_ERR_SPAWN;
    }
    lock(&tty->lock);
    tty->winsize.row = (word_t) rows;
    tty->winsize.col = (word_t) cols;
    unlock(&tty->lock);

    /* Its own session, so the first open of the tty below makes it the
     * controlling terminal — without that, Ctrl-C has nowhere to go. */
    sys_setsid();

    if (attach_tty_fd(task, 0, tty->num) < 0 ||
        attach_tty_fd(task, 1, tty->num) < 0 ||
        attach_tty_fd(task, 2, tty->num) < 0) {
        current = saved;
        pthread_mutex_unlock(&g_lock);
        return SOLOS_ISH_ERR_SPAWN;
    }

    err = do_execve(path, (size_t) argc, argv_buf, envp_buf);
    if (err < 0) {
        current = saved;
        pthread_mutex_unlock(&g_lock);
        return SOLOS_ISH_ERR_EXEC;
    }

    pthread_mutex_lock(&g_pty_lock);
    g_ptys[tty->num] = tty;
    pthread_mutex_unlock(&g_pty_lock);

    out->pid = (int) task->pid;
    out->pty_id = tty->num;
    task_start(task);
    current = saved;
    pthread_mutex_unlock(&g_lock);
    return SOLOS_ISH_OK;
}

int solos_ish_pty_input(int pty_id, const char *buf, int len) {
    struct tty *tty = pty_by_id(pty_id);
    if (tty == NULL) return SOLOS_ISH_ERR_ARGS;
    /* Non-blocking: a program that is not reading must not stall the UI. */
    ssize_t n = tty_input(tty, buf, (size_t) len, 0);
    return n < 0 ? (int) n : (int) n;
}

int solos_ish_pty_resize(int pty_id, int rows, int cols) {
    struct tty *tty = pty_by_id(pty_id);
    if (tty == NULL) return SOLOS_ISH_ERR_ARGS;
    lock(&tty->lock);
    tty_set_winsize(tty, (struct winsize_){.row = (word_t) rows, .col = (word_t) cols});
    unlock(&tty->lock);
    return SOLOS_ISH_OK;
}

int solos_ish_pty_close(int pty_id) {
    struct tty *tty = pty_by_id(pty_id);
    if (tty == NULL) return SOLOS_ISH_ERR_ARGS;
    lock(&tty->lock);
    tty_hangup(tty);
    unlock(&tty->lock);
    pthread_mutex_lock(&g_pty_lock);
    if (pty_id >= 0 && pty_id < SOLOS_MAX_PTYS) g_ptys[pty_id] = NULL;
    pthread_mutex_unlock(&g_pty_lock);
    return SOLOS_ISH_OK;
}

/* ------------------------------------------------------------------ */
/* Kill                                                                 */
/* ------------------------------------------------------------------ */

static int is_descendant_of(struct task *task, pid_t_ ancestor) {
    for (struct task *t = task; t != NULL; t = t->parent) {
        if (t->pid == ancestor) return 1;
    }
    return 0;
}

int solos_ish_kill_group(int pid) {
    if (!g_booted) return SOLOS_ISH_ERR_NOT_BOOTED;
    /* pid 1 is init: killing it takes the guest down with it. */
    if (pid <= 1) return SOLOS_ISH_ERR_ARGS;

    struct siginfo_ info = SIGINFO_NIL;
    int hits = 0;
    lock(&pids_lock);
    struct task *root = pid_get_task((dword_t)pid);
    pid_t_ pgid = root ? root->group->pgid : 0;
    for (int i = 2; i < MAX_PID; i++) {
        struct task *t = pid_get_task((dword_t)i);
        if (t == NULL) continue;
        int by_pgid = (pgid != 0 && t->group->pgid == pgid);
        if (by_pgid || is_descendant_of(t, (pid_t_)pid)) {
            send_signal(t, SIGKILL_, info);
            hits++;
        }
    }
    unlock(&pids_lock);
    return hits;
}

int solos_ish_signal_all(int stop) {
    if (!g_booted) return SOLOS_ISH_ERR_NOT_BOOTED;

    struct siginfo_ info = SIGINFO_NIL;
    int signal = stop ? SIGSTOP_ : SIGCONT_;
    int hits = 0;
    lock(&pids_lock);
    /* init is left running: it reaps children, and stopping it would leave
     * exits unobserved for as long as the guest is parked. */
    for (int i = 2; i < MAX_PID; i++) {
        struct task *t = pid_get_task((dword_t)i);
        if (t == NULL) continue;
        send_signal(t, signal, info);
        hits++;
    }
    unlock(&pids_lock);
    return hits;
}

/* ------------------------------------------------------------------ */
/* DNS                                                                  */
/* ------------------------------------------------------------------ */

/* Append the host's own resolver configuration — the search list first, then
 * one line per nameserver. Returns how many nameservers it found. */
static int host_resolv_conf(char *buf, size_t cap, size_t *pos) {
    struct __res_state res;
    memset(&res, 0, sizeof res);
    if (res_ninit(&res) != 0)
        return 0;

    if (res.dnsrch[0] != NULL) {
        size_t mark = *pos;
        *pos += (size_t)snprintf(buf + *pos, cap - *pos, "search");
        for (int i = 0; i < MAXDNSRCH && res.dnsrch[i] != NULL && *pos < cap - 64; i++)
            *pos += (size_t)snprintf(buf + *pos, cap - *pos, " %s", res.dnsrch[i]);
        *pos += (size_t)snprintf(buf + *pos, cap - *pos, "\n");
        if (*pos >= cap - 64) *pos = mark;
    }

    union res_sockaddr_union servers[MAXNS];
    int found = res_getservers(&res, servers, MAXNS);
    int written = 0;
    for (int i = 0; i < found && *pos < cap - 64; i++) {
        socklen_t len = servers[i].sin.sin_family == AF_INET6
            ? (socklen_t)sizeof servers[i].sin6
            : (socklen_t)sizeof servers[i].sin;
        if (servers[i].sin.sin_len == 0)
            continue;
        char address[NI_MAXHOST];
        if (getnameinfo((struct sockaddr *)&servers[i], len, address, sizeof address,
                        NULL, 0, NI_NUMERICHOST) != 0)
            continue;
        *pos += (size_t)snprintf(buf + *pos, cap - *pos, "nameserver %s\n", address);
        written++;
    }
    res_ndestroy(&res);
    return written;
}

/* The phone moves between wifi, cellular and VPNs while the guest is running,
 * and each of those hands out different resolvers. Network.framework reports
 * the change; set_dns rewrites nothing when the answer has not moved, so the
 * handler is cheap to fire. */
static nw_path_monitor_t g_path_monitor;

static void start_dns_watch(void) {
    if (g_path_monitor != NULL) return;
    g_path_monitor = nw_path_monitor_create();
    if (g_path_monitor == NULL) return;
    nw_path_monitor_set_queue(g_path_monitor, dispatch_get_global_queue(QOS_CLASS_UTILITY, 0));
    nw_path_monitor_set_update_handler(g_path_monitor, ^(nw_path_t path) {
        (void)path;
        solos_ish_set_dns(NULL);
    });
    nw_path_monitor_start(g_path_monitor);
}

int solos_ish_write_file(const char *path, const char *content, int length, int mode) {
    if (!g_booted) return SOLOS_ISH_ERR_NOT_BOOTED;
    if (!path || !content || length < 0) return SOLOS_ISH_ERR_ARGS;

    /* Same borrow as set_dns: `generic_open` reads `current`, which is NULL
     * on any thread that has never been a guest task. */
    pthread_mutex_lock(&g_lock);
    struct task *saved = current;
    current = pid_get_task(1);
    if (current == NULL) {
        current = saved;
        pthread_mutex_unlock(&g_lock);
        return SOLOS_ISH_ERR_NOT_BOOTED;
    }

    /* Missing parents are made first, as `mkdir -p` would (a mirror's
     * /etc/pip/pip.conf goes where the stock image has no /etc/pip).
     * An existing directory is not an error. */
    char parent[MAX_PATH];
    size_t plen = strlen(path);
    if (plen < sizeof(parent)) {
        memcpy(parent, path, plen + 1);
        for (char *p = parent + 1; *p; p++) {
            if (*p != '/') continue;
            *p = '\0';
            generic_mkdirat(AT_PWD, parent, 0755);
            *p = '/';
        }
    }

    struct fd *fd = generic_open(path, O_WRONLY_ | O_CREAT_ | O_TRUNC_, mode);
    if (IS_ERR(fd)) {
        int err = (int)PTR_ERR(fd);
        current = saved;
        pthread_mutex_unlock(&g_lock);
        return err;
    }
    /* A write may take less than it was given; a binary is written whole
     * or reported as failed, never left cut short. */
    int result = SOLOS_ISH_OK;
    for (int done = 0; done < length;) {
        ssize_t n = fd->ops->write(fd, (void *)(content + done), (size_t)(length - done));
        if (n <= 0) {
            result = n < 0 ? (int)n : SOLOS_ISH_ERR_ARGS;
            break;
        }
        done += (int)n;
    }
    fd_close(fd);
    current = saved;
    pthread_mutex_unlock(&g_lock);
    return result;
}

int solos_ish_set_dns(const char *nameservers) {
    if (!g_booted) return SOLOS_ISH_ERR_NOT_BOOTED;

    char buf[2048];
    size_t pos = 0;
    int count = 0;

    if (nameservers != NULL && *nameservers != '\0') {
        const char *p = nameservers;
        while (*p && pos < sizeof buf - 64) {
            const char *nl = strchr(p, '\n');
            size_t len = nl ? (size_t)(nl - p) : strlen(p);
            if (len > 0 && len < 64) {
                pos += (size_t)snprintf(buf + pos, sizeof buf - pos,
                                        "nameserver %.*s\n", (int)len, p);
                count++;
            }
            if (!nl) break;
            p = nl + 1;
        }
    } else {
        count = host_resolv_conf(buf, sizeof buf, &pos);
    }
    /* snprintf reports what it would have written, not what it did. */
    if (pos >= sizeof buf) pos = sizeof buf - 1;

    /* A guest with no resolver at all cannot even reach a captive portal, so
     * something has to go in the file. */
    if (count == 0)
        pos = (size_t)snprintf(buf, sizeof buf, "nameserver 8.8.8.8\nnameserver 8.8.4.4\n");

    /* Written through the guest's own filesystem so fakefs metadata stays
     * consistent, rather than poked into data/ behind its back. That reads
     * `current`, which is NULL on any thread that has never been a guest
     * task — so borrow init's, the way every other entry point here does. */
    pthread_mutex_lock(&g_lock);

    static char last[2048];
    if (pos == strlen(last) && memcmp(buf, last, pos) == 0) {
        pthread_mutex_unlock(&g_lock);
        return SOLOS_ISH_OK;
    }

    struct task *saved = current;
    current = pid_get_task(1);
    if (current == NULL) {
        current = saved;
        pthread_mutex_unlock(&g_lock);
        return SOLOS_ISH_ERR_NOT_BOOTED;
    }

    struct fd *fd = generic_open("/etc/resolv.conf", O_WRONLY_ | O_CREAT_ | O_TRUNC_, 0644);
    if (IS_ERR(fd)) {
        int err = (int)PTR_ERR(fd);
        current = saved;
        pthread_mutex_unlock(&g_lock);
        return err;
    }
    ssize_t written = fd->ops->write(fd, buf, pos);
    fd_close(fd);
    current = saved;

    if (written >= 0) {
        memcpy(last, buf, pos);
        last[pos] = '\0';
    }
    pthread_mutex_unlock(&g_lock);
    return written < 0 ? (int)written : SOLOS_ISH_OK;
}
